### ISSUE TITLE
Generate the HTML File

### ISSUE THREAD

**Issue by BismuthBetel** [BismuthBetel/portfolio-generator#2]
**Description**

- Build HTML template
- Generate HTML file

**Comment by NicholasBear97** [comment]
Hello, 

I am learning HTML/CSS/JS at the moment. I have experience with Java, C++, and C#, most to least in that order. I would like to help with this project if you are open to it.

Best,
Nicholas Bear

**Comment by BismuthBetel** [comment]
Hello,

You are welcome to fork the project if you'd like. I am also learning this material, so I would like to tackle each issue myself too. 

Thank you for reaching out.
Rebecca
